const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.WaitForPreviousActions
	];
};
self.C3_JsPropNameTable = [
	{girisek: 0},
	{lucekirgek: 0},
	{bilgiek: 0},
	{BTN_Genel: 0},
	{BTN_Ekran: 0},
	{BTN_Ses: 0},
	{Fare: 0},
	{Dokun: 0},
	{Ses: 0},
	{menuzemin: 0},
	{BTN_Seviye: 0},
	{BTN_Kapat: 0},
	{Txt_Hamle: 0},
	{Tarayıcı: 0},
	{YerelKayıtAlanı: 0},
	{cekirge1: 0},
	{cekirge2: 0},
	{dolu: 0},
	{deger: 0},
	{SPR_Kutu: 0},
	{SPR_Tebrikler: 0},
	{BTN_Hover: 0},
	{seviye: 0},
	{hamlesayisi: 0},
	{konumlar: 0},
	{fon: 0},
	{tiklandi: 0},
	{y: 0},
	{i: 0},
	{j: 0}
];

self.InstanceType = {
	girisek: class extends self.ISpriteInstance {},
	lucekirgek: class extends self.ISpriteInstance {},
	bilgiek: class extends self.ISpriteInstance {},
	BTN_Genel: class extends self.ISpriteInstance {},
	BTN_Ekran: class extends self.ISpriteInstance {},
	BTN_Ses: class extends self.ISpriteInstance {},
	Fare: class extends self.IInstance {},
	Dokun: class extends self.IInstance {},
	Ses: class extends self.IInstance {},
	menuzemin: class extends self.ISpriteInstance {},
	BTN_Seviye: class extends self.ISpriteInstance {},
	BTN_Kapat: class extends self.ISpriteInstance {},
	Txt_Hamle: class extends self.ITextInstance {},
	Tarayıcı: class extends self.IInstance {},
	YerelKayıtAlanı: class extends self.IInstance {},
	cekirge1: class extends self.ISpriteInstance {},
	cekirge2: class extends self.ISpriteInstance {},
	SPR_Kutu: class extends self.ISpriteInstance {},
	SPR_Tebrikler: class extends self.ISpriteInstance {},
	BTN_Hover: class extends self.ISpriteInstance {}
}